title: "카프카 핵심 가이드 (개정판)"
description: "『카프카 핵심 가이드: 대규모  실시간 데이터와 스트림 처리』 개정판 공식 페이지입니다. (2023년 4월 출간 예정) 오, 탈자 등 관련 정보는 모두 이곳에 게시됩니다."
markdown: kramdown
show_downloads: false
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
